### PR TITLE
Feature: adding hook to execute additional scripts on startup

### PR DESCRIPTION
**Pull request by williamsbdev**
This will close both #18 and #24.

The scripts are located in the /docker-entrypoint-initdb.d directory.

Paired on this with @benkiefer

### CODE REVIEW

**Comment by jgangemi** [comment]
is there any movement on this? i could really use the functionality this will provide.

**Comment by yosifkit** [comment]
I think @tianon was working on a set closer to what we have in the postgres image (to include bash scripts as well as sql), but this will still be very limited and needs documentation to cover the caveats.

**Comment by jgangemi** [comment]
is there another issue tracking this since you closed this one?

as a work around for anyone else, you could copy the entrypoint script that the container uses and append your init script contents to the end. if you're using `mysqldump` to create the file, be sure to use `--extended-insert=FALSE` and `--skip-comments`

**Comment by williamsbdev** [comment]
There is not another issue. I was working through the comments but no
progress was made after I addressed the issues they had. I'm leaving it up
to someone else to do this if it is needed and will continue to just use my
fork.

On Saturday, January 24, 2015, Jae Gangemi <notifications@github.com> wrote:

> is there another issue tracking this since you closed this one?
>
> as a work around for anyone else, you could copy the entrypoint script
> that the container uses and append your init script contents to the end. if
> you're using mysqldump to create the file, be sure to use
> --extended-insert=FALSE and --skip-comments
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker-library/mysql/pull/31#issuecomment-71327453>.
>


-- 
Sent from Gmail Mobile

**Comment by jgangemi** [comment]
then shouldn't it be enough to provide a link to the mysql docs for the `--init-file` option in the docs here and also include my comment above about the options to use for `mysqldump`?

if that's what it takes to get this into the official build, i'd be happy to create a pull request. if there's something else, please let me know and i can look to address it. having this as part of the official image would be extremely helpful to me (and i'm sure others).

**Comment by williamsbdev** [comment]
Go ahead and try that. LGTM. I gave up as I felt they wanted me to research
how the Postgres was working and change my implementation. I have it
working for myself felt it was sufficient to be merged.

On Saturday, January 24, 2015, Jae Gangemi <notifications@github.com> wrote:

> then shouldn't it be enough to provide a link to the mysql docs for the
> --init-file option in the docs here and also include my comment above
> about the options to use for mysqldump?
>
> if that's what it takes to get this into the official build, i'd be happy
> to create a pull request. if there's something else, please let me know and
> i can look to address it. having this as part of the official image would
> be extremely helpful to me (and i'm sure others).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker-library/mysql/pull/31#issuecomment-71328843>.
>


-- 
Sent from Gmail Mobile

**Pull request closed without merging**
