### PR TITLE
Allow creation of multiple databases

### PR DESCRIPTION
**Pull request by victorhahncastell**
See amended documentation at https://github.com/victorhahncastell/docker-docs/tree/master/mysql. Matching pull request will go to docker-library/docs

### CODE REVIEW

**Comment by yosifkit** [comment]
This seems a bit complex for an official image and I would rather recommend that a user just write a startup script to creates all the users, databases, and permissions that they need, but I'll defer to @ltangvald since he is from upstream and helps manage these images.

**Comment by tianon** [comment]
I agree, this is incredibly complex (both the implementation and the user
experience).

**Comment by victorhahncastell** [comment]
Thanks for your feedback! I agree the implementation is a bit complex--it probably shows that I don't write shell scripts every day. I don't quite see though how the user experience is overly complicated, took me three sentences to amend the documentation.

**Comment by ltangvald** [comment]
I agree the implementation is too complex. User experience seems ok, though ideally we'd have something that isn't any different to use whether you want 1 or more databases (e.g. you supply a delimited list to a single variable). I'll see if I can pick some brains about it (though almost everyone is on vacation at the moment).
If we can't find a clean way to implement it, finding a good solution to issue #24 might be a decent compromise.

**Comment by ltangvald** [comment]
Is this now adequately solved by the support for running arbitrary init scripts during database creation?

**Comment by asymmetric** [comment]
I think the answer to @ltangvald's question is yes, this and #18 should be closed since we can drop scripts in `/docker-entrypoint-initdb.d`.

**Comment by victorhahncastell** [comment]
Guess I should comment on this as this is my PR -- though I don't really have any opinion on this as my work currently does not involve this project any more. Feel free to close :-)

**Comment by yosifkit** [comment]
:+1:

**Comment by mrts** [comment]
And here's a sample script and README with instructions for creating any number of databases during initialization by mounting a volume into `/docker-entrypoint-initdb.d`:
https://github.com/mrts/docker-posgresql-multiple-databases

**Pull request closed without merging**
