### PR TITLE
Add --setopt=skip_missing_names_on_install=False to "yum install"

### PR DESCRIPTION
**Pull request by tianon**
See https://unix.stackexchange.com/a/477127/153467 for details 🙈

### CODE REVIEW

**Comment by Djelibeybi** [comment]
We disable the UEK repos inside the container images so that customers don't try and install a kernel inside a container. To install it, you will have to enable the repo on-the-fly:

```shell
$ yum --enablerepo=ol7_UEKR6 install -y libzstd
Loaded plugins: ovl
ol7_UEKR6                                                                                                    | 3.0 kB  00:00:00
ol7_latest                                                                                                   | 3.6 kB  00:00:00
(1/5): ol7_UEKR6/x86_64/updateinfo                                                                           | 535 kB  00:00:00
(2/5): ol7_latest/x86_64/group_gz                                                                            | 136 kB  00:00:00
(3/5): ol7_latest/x86_64/updateinfo                                                                          | 3.4 MB  00:00:00
(4/5): ol7_UEKR6/x86_64/primary_db                                                                           |  41 MB  00:00:02
(5/5): ol7_latest/x86_64/primary_db                                                                          |  40 MB  00:00:01
Resolving Dependencies
--> Running transaction check
---> Package libzstd.x86_64 0:1.4.4-1.el7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

===============================================================================================================================================================================================================================================================
 Package                                                     Arch                                                       Version                                                            Repository                                                     Size
===============================================================================================================================================================================================================================================================
Installing:
 libzstd                                                     x86_64                                                     1.4.4-1.el7                                                        ol7_UEKR6                                                     259 k

Transaction Summary
===============================================================================================================================================================================================================================================================
Install  1 Package

Total download size: 259 k
Installed size: 682 k
Is this ok [y/d/N]: y
Downloading packages:
libzstd-1.4.4-1.el7.x86_64.rpm                                                                                                                                                                                                          | 259 kB  00:00:00
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : libzstd-1.4.4-1.el7.x86_64                                                                                                                                                                                                                  1/1
  Verifying  : libzstd-1.4.4-1.el7.x86_64                                                                                                                                                                                                                  1/1

Installed:
  libzstd.x86_64 0:1.4.4-1.el7

Complete!
bash-4.2#
```

But, at least it doesn't pull in any dependencies, like a kernel. :)

**Comment by tianon** [comment]
Heh, but that's just `libzstd`, and I need the command-line tool `zstd` :innocent:

**Comment by Djelibeybi** [comment]
Ha, I misunderstood the question. One moment, I'm checking.

**Comment by Djelibeybi** [comment]
It's in our EPEL repo, so:

```shell
yum -y install oracle-epel-release-el7
yum -y install zstd
```

**Comment by tianon** [comment]
Yay, it works!  Thank you :blush:

**Pull request merged**
