### PR TITLE
Made charset and collate customizable, with utf8 as default.

### PR DESCRIPTION
**Pull request by OmarIthawi**
I was a little bit frustrated that this docker instance creates a `latin1` database by default. I needed a way to customize it.

TODO:
* [ ]  Update the documentation, but would like to get feedback on this PR if possible.

### CODE REVIEW

**Comment by Zophar78** [comment]
Exactly what i was looking for!!! +1
But it has already done a lot of noise here: https://github.com/docker-library/mysql/pull/14

**Comment by OmarIthawi** [comment]
I've used it and liked it. But looks like the community have other requirements as discussed in #14.

I'm closing this for now.

**Comment by ltangvald** [comment]
You might add your thoughts there. Also take a look at the ability to pass any server option to the image, and see if that would help in your case.

**Comment by OmarIthawi** [comment]
@ltangvald My requirements were very simple. I needed the default database to be UTF-8 and got that with this PR. It's up to the repo owner to decide whether to take the PR or not :).

**Comment by OmarIthawi** [comment]
@ltangvald I saw the efforts on the server locale. But I'm not sure that I would need it. Thanks :)

**Pull request closed without merging**
