### PR TITLE
Ensure that /var/run/mysqld directory exists

### PR DESCRIPTION
**Pull request by giggsoff**
We create directory in /var/run during image creation, but for example containerd [mount](https://github.com/lf-edge/eve/blob/master/pkg/pillar/vendor/github.com/containerd/containerd/oci/spec.go#L201-L206) tmpfs on /run directory. We can lose content of directory in this case, so we must ensure that it exists.

Signed-off-by: Petr Fedchenkov <giggsoff@gmail.com>

fixes https://github.com/docker-library/mysql/issues/562

### CODE REVIEW

**Comment by tianon** [comment]
Thanks!

I think instead of hard-coding `/var/run/mysqld`, we should probably check the relevant configuration flag values (like we do for `datadir`).  In this case, I think that's going to be the directory portion of both `pid-file` and `socket`.

I also think we should include this as part of the existing `docker_create_db_directories` function.  It's a bit verbose, but maybe something like this:

```bash
# creates folders for the database
# also ensures permission for user mysql if run as root
docker_create_db_directories() {
	local user; user="$(id -u)"

	local -A dirs=( ["$DATADIR"]=1 )
	local dir
	dir="$(dirname "$SOCKET")"
	dirs["$dir"]=1

	# TODO /var/lib/mysql-files and /var/lib/mysql-keyring ?
	# see https://github.com/docker-library/mysql/issues/562

	# "datadir" and "socket" are already handled above (since they were already queried previously)
	local conf
	for conf in \
		general-log-file \
		pid-file \
		slow-query-log-file \
	; do
		dir="$(mysql_get_config "$conf" "$@")"
		dir="$(dirname "$dir")" # each of these config options points at a file
		dirs["$dir"]=1
	done

	mkdir -p "${!dirs[@]}"

	if [ "$user" = "0" ]; then
		# this will cause less disk access than `chown -R`
		find "${!dirs[@]}" \! -user mysql -exec chown mysql '{}' +
	fi
}
```

Which also means we need to change the usage further down to include `"$@"`:

```bash
		mysql_check_config "$@"
		# Load various environment variables
		docker_setup_env "$@"
		docker_create_db_directories "$@"
```

Please let me know if you'd like to continue working on this or if you'd rather have us take over. :+1:

**Comment by giggsoff** [comment]
Thank you for your comments! It looks reasonable to not hardcode paths, so, I use your suggested code and also add check for absolute path received from dirname (to not handle "." from dirname command).

**Comment by yosifkit** [comment]
Rebased and added in `secure_file_priv` too.

cc @tianon and @ltangvald Does this seem good to go? Should we also add `keyring-file-data` (default: `/var/lib/mysql-keyring/keyring`), so it is also accounted for? It only appears in the help output if the plugin is loaded with `--early-plugin-load=keyring_file.so`.

**Comment by tianon** [comment]
Oh, nice find on `keyring-file-data` - IMO we should add it, yeah (and probably use `case` instead of `if !=` so it's easier to maintain if the list grows).

**Comment by yosifkit** [comment]
Added `keyring-file-data` and switched to a `case` statement.

**Review by tianon — APPROVED** [review]

**Comment by tianon** [comment]
@ltangvald I'm going to merge this, but please feel free to let us know if you don't like it and we can revert / continue discussing :heart:

**Pull request merged**
