### PR TITLE
load time zones into mysql

### PR DESCRIPTION
**Pull request by phemmer**
This enables time-zone support in mysql.

https://dev.mysql.com/doc/refman/5.7/en/time-zone-support.html

### CODE REVIEW

**Comment by yosifkit** [comment]
LGTM

**Comment by yosifkit** [comment]
ping @ltangvald

**Comment by ltangvald** [comment]
I'm not familiar with the bug in question, but shouldn't the workaround be for both 5.5 and 5.6 (bug was first reported for 5.0)?

Otherwise it looks good.

**Comment by phemmer** [comment]
> I'm not familiar with the bug in question, but shouldn't the workaround be for both 5.5 and 5.6 (bug was first reported for 5.0)?

I manually tested it on each of the versions, and 5.6 is the only one currently affected.

**Comment by ltangvald** [comment]
LGTM.
Guess the weirdness of the 5.5-image sometimes works in our favor :P

**Comment by tianon** [comment]
Can you update this to include the `--protocol` change from #84?  If not, that's alright -- I can do it post merge instead if you'd prefer. :+1:

**Comment by phemmer** [comment]
@tianon Done.

**Comment by tianon** [comment]
Thanks! :+1:

**Pull request merged**
