### PR TITLE
Added "bzip2" so we can import .sql.bz2 dumps.

### PR DESCRIPTION
**Pull request by woutersamaey**
Follow-up to #851

### CODE REVIEW

**Comment by tianon** [comment]
Nice catch!  Can we move this down to be in the same block of package installs as the `bzip2` cohorts, `zstd` and `xz-utils`? :innocent:

(The lists of packages should also be sorted alphabetically, so this will go at the top of the block of packages lower down.)

If you'd rather, I'd also be happy to take over this change from here. :+1:

**Comment by woutersamaey** [comment]
I can do it on monday (if my day isn’t too hectic), but if you can do it faster then by all means, go ahead!

**Comment by woutersamaey** [comment]
@tianon I moved the package further down the file and should be OK now?

**Comment by tianon** [comment]
Force pushed to fix whitespace and update Oracle variants too :+1: :heart:

**Comment by woutersamaey** [comment]
This PR is merged and closed, but I'm still seeing issues with tag `mysql:5.7-debian`. Is Dockerhub not updated somehow?
Or is there a delay?
How can I make sure I got the latest version of `mysql:5.7-debian`

**Pull request merged**
