### PR TITLE
Skip setup if they want to get --help

### PR DESCRIPTION
**Pull request by yosifkit**
This will allow users to see available flags with `docker run -it --rm mysql --verbose --help`.

### CODE REVIEW

**Comment by tianon** [comment]
@ltangvald what're your thoughts on this?  Right now it falls over pretty hard if we use `--help`...  (tries to initialize a database, etc)

Do you think there are other `mysqld` options we should add to the "bypass" list? (maybe start with this and keep our eyes open for more examples as we go?)

**Comment by ltangvald** [comment]
Maybe --print-defaults?

**Comment by ltangvald** [comment]
A concern is that this will quickly balloon out of control if we start adding checks for any options that cause the server to behave in a non-standard way. E.g. -? is a variant of --help and would also need to be included. Maybe better to either try to detect the failure early so the user doesn't have to wait for a timeout or have a specific, documented way of getting a readme-like output from the image?

**Comment by yosifkit** [comment]
It could get longer, yes, but I think there is a limited set that cause the server to not actually run that we should catch, rather than trying to detect that a failure is a success. We would otherwise have to detect them in two spots, one after trying to get `DATADIR` and skip the rest of the setup, and the other would be when we start the server in the background, which could've failed for other reasons.

The set I have found is: `-'?'|--help|--print-defaults|-V|--version`.  The user will have to be aware that `--print-defaults` needs to be the first argument, but that is in the verbose help output and should not be something we need to explicitly test for.

**Comment by yosifkit** [comment]
@ltangvald, does this seem like a solid solution?

**Comment by ltangvald** [comment]
Gah, sorry. Yeah as long as we keep it limited it looks good :)

**Comment by tianon** [comment]
LGTM :+1:

**Pull request merged**
