### PR TITLE
Added environment variable to run SQL command at initialization phase

### PR DESCRIPTION
**Pull request by robvadai**

### CODE REVIEW

**Comment by yosifkit** [comment]
What functionality is gained that is not handled by just adding a `custom.sql` to `/docker-entrypoint-initdb.d/`?  I'd rather not complicate the image with another environment variable without a strong use case.

Thoughts? @ltangvald or @tianon

**Comment by robvadai** [comment]
@yosifkit if you define a bash script you have to construct the full mysql command with username etc. Using this environment variable saves you doing all this.

**Comment by yosifkit** [comment]
You don't need a bash script; it'll import sql and sql.gz files directly: https://github.com/docker-library/mysql/blob/958442857411934f3f3a525325a2e10c7e8e8155/8.0/docker-entrypoint.sh#L128-L129.

**Comment by ltangvald** [comment]
Yeah, I don't think this adds anything that isn't already supported (plus it's only been added for 5.5)

**Comment by robvadai** [comment]
I got it. It should be added to the README then to make it clear. Thanks guys

**Pull request closed without merging**
