### PR TITLE
Support for sql.gz dump restore

### PR DESCRIPTION
**Pull request by silentroach**
It is faster sometimes to restore .sql.gz dumps. For example if you use docker-machine + virtualbox with dumps mounted via shared folders.

### CODE REVIEW

**Comment by ovr** [comment]
:+1:

**Comment by tianon** [comment]
LGTM

cc @ltangvald

**Comment by silentroach** [comment]
is something wrong with pr? it is open more than a month

**Comment by ltangvald** [comment]
Sorry, that's on me :|
@tianon Looks good to me

**Comment by silentroach** [comment]
thank you

**Comment by ltangvald** [comment]
Thanks for the contribution! :)

**Pull request merged**
