### PR TITLE
Support running server with autocommit

### LINKED ISSUE #816: mysql:8.0.28: cannot boot server with autocommit=0
mysql:8.0.28 (NG)

```
# docker run -ti -e MYSQL_RANDOM_ROOT_PASSWORD=1 mysql:8.0.28 --autocommit=0
2022-01-26 07:09:45+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.28-1debian10 started.
2022-01-26 07:09:45+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
2022-01-26 07:09:45+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.28-1debian10 started.
2022-01-26 07:09:45+00:00 [Note] [Entrypoint]: Initializing database files
2022-01-26T07:09:45.498162Z 0 [System] [MY-013169] [Server] /usr/sbin/mysqld (mysqld 8.0.28) initializing of server in progress as process 42
2022-01-26T07:09:45.510419Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
2022-01-26T07:09:45.986800Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
2022-01-26T07:09:47.489186Z 6 [Warning] [MY-010453] [Server] root@localhost is created with an empty password ! Please consider switching off the --initialize-insecure option.
2022-01-26T07:09:48.490082Z 6 [ERROR] [MY-000061] [Server] 1694  Cannot modify @@session.sql_log_bin inside a transaction.
2022-01-26T07:09:48.493835Z 0 [ERROR] [MY-013236] [Server] The designated data directory /var/lib/mysql/ is unusable. You can remove all files that the server added to it.
2022-01-26T07:09:48.493906Z 0 [ERROR] [MY-010119] [Server] Aborting
2022-01-26T07:09:50.256083Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.28)  MySQL Community Server - GPL.
```

mysql:8.0.27 (OK)

```
# docker run -ti -e MYSQL_RANDOM_ROOT_PASSWORD=1 mysql:8.0.27 --autocommit=0
2022-01-26 07:09:53+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.27-1debian10 started.
2022-01-26 07:09:53+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
2022-01-26 07:09:53+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.27-1debian10 started.
2022-01-26 07:09:53+00:00 [Note] [Entrypoint]: Initializing database files
2022-01-26T07:09:53.902070Z 0 [System] [MY-013169] [Server] /usr/sbin/mysqld (mysqld 8.0.27) initializing of server in progress as process 43
2022-01-26T07:09:53.914265Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
2022-01-26T07:09:54.405108Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
2022-01-26T07:09:55.476839Z 0 [Warning] [MY-013746] [Server] A deprecated TLS version TLSv1 is enabled for channel mysql_main
2022-01-26T07:09:55.476899Z 0 [Warning] [MY-013746] [Server] A deprecated TLS version TLSv1.1 is enabled for channel mysql_main
2022-01-26T07:09:55.529705Z 6 [Warning] [MY-010453] [Server] root@localhost is created with an empty password ! Please consider switching off the --initialize-insecure option.
2022-01-26 07:09:58+00:00 [Note] [Entrypoint]: Database files initialized
2022-01-26 07:09:58+00:00 [Note] [Entrypoint]: Starting temporary server
mysqld will log errors to /var/lib/mysql/7f03fb4b8b17.err
mysqld is running as pid 92
2022-01-26 07:09:59+00:00 [Note] [Entrypoint]: Temporary server started.
Warning: Unable to load '/usr/share/zoneinfo/iso3166.tab' as time zone. Skipping it.
Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
Warning: Unable to load '/usr/share/zoneinfo/zone.tab' as time zone. Skipping it.
Warning: Unable to load '/usr/share/zoneinfo/zone1970.tab' as time zone. Skipping it.
2022-01-26 07:10:02+00:00 [Note] [Entrypoint]: GENERATED ROOT PASSWORD: waevohth3ahZiciageF8jookahmoox5m
  :
```

environment = Docker Desktop for mac 4.4.2 (73305)

```
# docker version
Client:
 Cloud integration: v1.0.22
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:46:56 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.12
  Git commit:       459d0df
  Built:            Mon Dec 13 11:43:56 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### PR DESCRIPTION
**Pull request by LaurentGoderre**
Forces initiation queries to run in autocommit then use the provided mode

Fixed #816

### CODE REVIEW

**Comment by tianon** [comment]
Doh, sorry, this one got lost -- I worry that this "leaks" to users since their scripts get run in this environment too, so I think I'd prefer if we change our one or two scripts to instead enable autocommit (since IIRC there's a trivial one-line way to do so for a single session).  It might also be worth trying to make sure we minimize the number of queries we actually make, but maybe we've already done that. :see_no_evil:

**Comment by LaurentGoderre** [comment]
@tianon sadly no you can't use that one liner in a session (or I didn't get it working after trying many ways). I tested the change and posted the result and it respected the flag that was passed.

**Comment by tianon** [comment]
Wow, that's bizarre -- I've confirmed, every way I can find or think of to `SET autocommit = 1` (with or without `SESSION` qualifiers) and even adding an explicit `COMMIT` still ends up with `Cannot modify @@session.sql_log_bin inside a transaction.` :sob:

That's wild, and seems unintentional?  Effectively this means it must be impossible to set autocommit to off by default, but turn it back on for a single session, which isn't a limitation that's documented anywhere I can find. :thinking:

**Comment by tianon** [comment]
To clarify though, my concern is not that the final runtime environment is correct (that much is clear from your change), but that the intermediate environment in which the user-supplied initdb scripts get invoked is _also_ disabling autocommit by default (because I think that's part of the "user intent" expressed by passing this flag by default globally).

**Comment by tianon** [comment]
Now I'm questioning my testing methodology entirely though, because even deleting the `SQL_LOG_BIN` bit from the script completely still gives the exact same `Cannot modify @@session.sql_log_bin inside a transaction.` error. :thinking:

**Comment by LaurentGoderre** [comment]
@tianon glad it's not just me! I spent a while trying to get it work that way

**Comment by tianon** [comment]
Hahahahahahahahahahaha: https://github.com/mysql/mysql-server/commit/7dbf4f80ed15f3c925cfb2b834142f23a2de719a / https://bugs.mysql.com/bug.php?id=110535

Turns out this was a bug in `--initialize-insecure` that still exists in MySQL 8.0 but was fixed in 8.2+ (@yosifkit was trying to gaslight me saying it works fine but he was testing 8.4 and I was testing 8.0, but that provided the clue that helped find the upstream code).

**Comment by tianon** [comment]
```diff
diff --git a/docker-entrypoint.sh b/docker-entrypoint.sh
index 8cb17c4..e635e07 100755
--- a/docker-entrypoint.sh
+++ b/docker-entrypoint.sh
@@ -214,7 +214,8 @@ docker_create_db_directories() {
 # initializes the database directory
 docker_init_database_dir() {
 	mysql_note "Initializing database files"
-	"$@" --initialize-insecure --default-time-zone=SYSTEM
+	"$@" --initialize-insecure --default-time-zone=SYSTEM --autocommit=1
+	# explicitly enable autocommit to combat https://bugs.mysql.com/bug.php?id=110535 (TODO remove this when 8.0 is EOL; see https://github.com/mysql/mysql-server/commit/7dbf4f80ed15f3c925cfb2b834142f23a2de719a)
 	mysql_note "Database files initialized"
 }
 
@@ -292,6 +293,9 @@ docker_setup_db() {
 
 	# tell docker_process_sql to not use MYSQL_ROOT_PASSWORD since it is just now being set
 	docker_process_sql --dont-use-mysql-root-password --database=mysql <<-EOSQL
+		-- enable autocommit explicitly (in case it was disabled globally)
+		SET autocommit = 1;
+
 		-- What's done in this file shouldn't be replicated
 		--  or products like mysql-fabric won't work
 		SET @@SESSION.SQL_LOG_BIN=0;
```

**Comment by LaurentGoderre** [comment]
Done!

**Review by tianon — APPROVED** [review]

**Comment by yosifkit** [comment]
I thought we might've missed the other `docker_process_sql` statements, but `CREATE` and `GRANT` statements already [implicitly commit](https://dev.mysql.com/doc/refman/8.4/en/implicit-commit.html) and `mysql_tzinfo_to_sql` ends its output with an explicit `COMMIT;`.

https://github.com/docker-library/mysql/blob/1a703318803fa85bf69cb5d2e5b3f1c4087627b5/docker-entrypoint.sh#L266-L269
https://github.com/docker-library/mysql/blob/1a703318803fa85bf69cb5d2e5b3f1c4087627b5/docker-entrypoint.sh#L311-L324

**Pull request merged**
