### PR TITLE
update debian base version to buster

### PR DESCRIPTION
**Pull request by inductor**
It's been a while since buster released

### CODE REVIEW

**Comment by yosifkit** [comment]
> E: Version '5.6.47-1debian10' for 'mysql-server' was not found

It seems that 5.6 isn't packaged for Buster, so it will have to stay on Stretch. I think just adjusting line 14 in `update.sh` to be `[5.6]='stretch'` and running `update.sh` should do it.

@tianon and @ltangvald, any other comments or concerns on bumping the OS?

**Comment by tianon** [comment]
Do we need to worry about anything like https://github.com/docker-library/postgres/issues/582? (locale changes in glibc that manifest in buster+)

**Comment by inductor** [comment]
@yosifkit @tianon

Updated the shell!

**Comment by tianon** [comment]
> Do we need to worry about anything like [docker-library/postgres#582](https://github.com/docker-library/postgres/issues/582)? (locale changes in glibc that manifest in buster+)

friendly ping @ltangvald -- is this something we need to worry about, or does MySQL handle locales differently such that it's not a concern?

**Comment by ltangvald** [comment]
Hm, I vaguely remember thinking there might be some issue with updating from stretch to buster, but I can't remember what it might have been (maybe just that we dropped 32bit support for buster, which wouldn't matter)

**Comment by ltangvald** [comment]
Checked with the devs, and no, MySQL should not be affected by that PG issue.

**Comment by tianon** [comment]
That's excellent! 🥳

So we're good to go, or you want to rack your brain a bit to try and remember what you had in mind? 😅

**Comment by ltangvald** [comment]
No, I think we're good to go :)

**Pull request merged**
